services:

  db:
    container_name: db
    image: mysql:8.0
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 1234:80
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: always
    working_dir: /var/www
    volumes:
      - ../app:/var/www
    depends_on:
      - db
    ports:
      - 8000:8000
    command: sh -c "if [ ! -f artisan ]; then composer create-project laravel/laravel . --prefer-dist --no-install; fi && if [ ! -d vendor ]; then composer install; fi && php artisan serve --host=0.0.0.0 --port=8000"
